language: cpp

sudo: required
dist: focal

notifications: 
  email:
    recipients:
    - rncbc@rncbc.org
    on_success: change
    on_failure: always

branches:
  only:
  - master

before_install:
- sudo add-apt-repository --yes ppa:rncbc/focal
- sudo apt-get update -qq

install:
- sudo apt-get install -qq qtbase5-static; source /opt/qtbase5-static/*/bin/qtbase5-static-env.sh
- sudo apt-get install -qq libjack-dev libasound2-dev liblo-dev lv2-dev

before_script:
- git fetch --unshallow --tags -q
- ./autogen.sh

script:
- ./configure
- make
- sudo make install
