language: cpp

sudo: required
dist: focal

notifications: 
  email:
    recipients:
    - rncbc@rncbc.org
    on_success: change
    on_failure: always

branches:
  only:
  - master

before_install:
- sudo add-apt-repository --yes ppa:rncbc/libs-focal
- sudo apt-get update -qq

install:
- sudo apt-get install -qq qtbase5-static qttools5-static
- sudo apt-get install -qq qtwayland5-static qtsvg5-static
- sudo apt-get install -qq qttranslations5-static
- sudo apt-get install -qq libjack-dev libasound2-dev lv2-dev liblo-dev

before_script:
- git fetch --unshallow --tags -q

script:
- source /opt/qtbase5-static/*/bin/qtbase5-static-env.sh
- cmake .
- make
- sudo make install
